name: rabpro
channels:
  - jschwenk
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - gdal
  - numpy
  - geopandas=0.7.0
  - matplotlib
  - pyproj
  - shapely
  - rivgraph=0.3
  - requests
  - appdirs
  - earthengine-api
