name: rabpro
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - gdal
  - numpy
  - geopandas=0.7.0
  - scikit-image
  - opencv
  - pyproj
  - shapely
  - requests
  - appdirs
  - earthengine-api
  - tqdm
  - beautifulsoup4
