name: rabpro
channels:
  - jschwenk
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - gdal
  - osgeo
  - numpy
  - geopandas=0.7.0
  - scikit-image
  - opencv
  - matplotlib
  - pyproj
  - shapely
  - rivgraph=0.3
  - requests
  - appdirs
  - earthengine-api
