name: rabpro
channels:
  - jschwenk
  - conda-forge
  - defaults
dependencies:
  - python
  - gdal
  - numpy
  - scikit-image
  - geopandas>=0.7
  - opencv
  - networkx
  - matplotlib
  - pyproj
  - shapely
  - fiona
  - rivgraph>=0.3
  - fastdtw
  - rasterstats
  - rasterio
  - ipython=7.15
  - spyder
