name: build
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "rabpro/**"
      - "tests/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "rabpro/**"
      - "tests/**"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          miniconda-version: "latest"
          activate-environment: rabpro
          environment-file: environment.yml
          channels: jschwenk, conda-forge, defaults
          auto-activate-base: false

      - name: Install dependencies and rabpro
        run: |
          conda info
          pip install coverage
          python3 setup.py install

      - name: Set up credentials (Linux & macOS)
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: |
          mkdir -p "$HOME/.config/earthengine"
          echo "$EARTH_ENGINE_KEY" > "$HOME/.config/earthengine/credentials"
        env:
          EARTH_ENGINE_KEY: ${{ secrets.EARTH_ENGINE_SECRET }}

      - name: Set up credentials (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir -p "$USERPROFILE/.config/earthengine"
          echo "$EARTH_ENGINE_KEY" > "$USERPROFILE/.config/earthengine/credentials"
        env:
          EARTH_ENGINE_KEY: ${{ secrets.EARTH_ENGINE_SECRET }}

      - name: Set up data (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir -p "$HOME/.local/share/rabpro"
          cp -r ./tests/data/DEM ./tests/data/HydroBasins "$HOME/.local/share/rabpro/"

      - name: Set up data (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          mkdir -p "$HOME/Library/Application Support/rabpro"
          cp -r ./tests/data/DEM ./tests/data/HydroBasins "$HOME/Library/Application Support/rabpro/"

      - name: Set up data (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir -p "$USERPROFILE/AppData/Local/jschwenk/rabpro"
          cp -r ./tests/data/DEM ./tests/data/HydroBasins "$USERPROFILE/AppData/Local/rabpro/rabpro/"

      - name: Run unit tests
        run: |
          coverage run -m unittest tests/test.py
          coverage report -m
