name: build
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "rabpro/**"
      - "tests/**"
      - .coveragerc
      - setup.py
  pull_request:
    paths:
      - "rabpro/**"
      - "tests/**"
      - .coveragerc
      - setup.py

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] #, macos-latest, windows-latest] # undo once ubuntu works
        python-version: [3.8] #[3.7, 3.8, 3.9] # undo once rivgraph dep removed
        include:
          - os: ubuntu-latest
            credentials-path: ~/.config/earthengine
            data-path: ~/.local/share/rabpro/

          #- os: macos-latest
          #  credentials-path: ~/.config/earthengine
          #  data-path: ~/Library/Application Support/rabpro/

          #- os: windows-latest
          #  credentials-path: $USERPROFILE/.config/earthengine
          #  data-path: $USERPROFILE/AppData/Local/rabpro/rabpro/

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}
          restore-keys: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-

      - name: Set up conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          miniconda-version: "latest"
          activate-environment: rabpro
          environment-file: environment.yml
          channels: jschwenk, conda-forge, defaults
          auto-activate-base: false
          use-only-tar-bz2: true # needs to be set for caching to work

      - name: Install dependencies and rabpro
        run: |
          conda info
          pip install coverage
          pip install .

      - name: Set up credentials
        run: |
          mkdir -p "$CREDENTIALS_PATH"
          echo "$EARTH_ENGINE_KEY" > "${CREDENTIALS_PATH}/credentials"
        env:
          EARTH_ENGINE_KEY: ${{ secrets.EARTH_ENGINE_SECRET }}
          CREDENTIALS_PATH: ${{ matrix.credentials-path }}

      - name: Set up data and run unit tests
        run: |
          mkdir -p "$DATA_PATH"
          cp -r ./tests/data/DEM ./tests/data/HydroBasins "$DATA_PATH"
          echo $DATA_PATH
          ls -al -- $DATA_PATH/**
          coverage run -m unittest tests/test.py
          coverage report -m
        env:
          DATA_PATH: ${{ matrix.data-path }}
