name: Add comment
on:
  issues:
    types:
      - labeled
jobs:
  add-comment:
    if: github.event.label.name == 'data request'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thank you for the request. Maintainers can take the following steps to accept the request:
            * [ ] upload to GEE with `rabpro.utils.upload_gee_tif_asset`
            * [ ] add an entry to [Data/user_gee_datasets.json](Data/user_gee_datasets.json)
            * [ ] test with `rabpro.subbasin_stats.main`